name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up repository
      uses: actions/checkout@v4
      with:
        submodules: false
        show-progress: false
    - name: Set up compiler
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        # When changing this update what Windows grabs too!
        release: '13.2.Rel1'    
    - name: Build
      run: make submodules && make -j$(nproc) all-boards && make drop-pkg
    - name: Extract version identifier
      run: |
        echo >> $GITHUB_ENV "UF2_VERSION_BASE=`git describe --dirty --always --tags`"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with: 
        path: build/uf2-samdx1-${{ env.UF2_VERSION_BASE }}.zip
        name: uf2-samdx1-${{ env.UF2_VERSION_BASE }}.zip
